name: kollab_contacts
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kollab_theme: 0.0.5
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
